---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: kube-system
spec:
  basicAuth:
    namespace: kube-system
    secret: traefik-auth

---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-auth
  namespace: kube-system
data:
  users: |1
   YWRtaW46JGFwcjEkRFBUQWpBYTUkSi93UW05SGRTMTE1LmVzdU5YbXN2Lw==
