apiVersion: v1
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-19T15:56:33Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:traefik.toml: {}
    manager: kubectl-create
    operation: Update
    time: "2021-07-19T15:56:33Z"
  name: traefik-conf
  namespace: kube-system
  resourceVersion: "1798093"
  uid: feb5701d-6cde-448b-9e99-07d45adbf93f

