apiVersion: v1
data:
  # Please note that tls.crt field must have value that you get after execute command:
  # cat tls.crt | base64 -w0
  # Repeat the same command for tls.key field:
  # cat tls.key | base64 -w0
  tls.crt: <Resultado obtido no seu comando no arquivo tls.crt>
  tls.key: <Resultado obtido no seu comando no arquivo tls.key>
kind: Secret
metadata:
  creationTimestamp: "2021-07-19T15:54:45Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:tls.crt: {}
        f:tls.key: {}
      f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2021-07-19T15:54:45Z"
  name: traefik-cert
  namespace: kube-system
  resourceVersion: "1797675"
  uid: bd5d1536-dbbb-4d57-a0ae-f5662dc30c1f
type: Opaque
