apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdIakNDQlFhZ0F3SUJBZ0l
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2l
kind: Secret
metadata:
  creationTimestamp: "2021-07-19T15:54:45Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:tls.crt: {}
        f:tls.key: {}
      f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2021-07-19T15:54:45Z"
  name: traefik-cert
  namespace: kube-system
  resourceVersion: "1797675"
  uid: bd5d1536-dbbb-4d57-a0ae-f5662dc30c1f
type: Opaque

